FILE_TITLE: "RADAR: analisi dati anno 2024"
chp_1:
    number: 1
    title: Traffico medio giornaliero
    text: RADAR_testo_Cap1.txt
    data_to_load:
        table_1:
            filename: TGM.csv
            columns_to_filter: ['Date', 'Veicoli', 'V media[km/h]', '(%)TGM M.P.', '(%)Velocità M.P.']
            set_index: Date
            columns_to_rename: {Veicoli: TGM}
            label: Conteggio e variazione percentuale TGM e velocità media da mese precedente (M.P.)
            table_limit: [37, 11]

        table_2:
            filename: TGM.csv
            columns_to_filter: [Date, TGM Leggeri]
            set_index: Date
            columns_to_rename: {Veicoli: TGM2}
            label: Conteggio
            table_limit: [90, 11]

    image_to_print:
        image_1:
            filename: TGM.csv
            set_index: Date
            columns_to_filter: ['Andamento da Gennaio(%)', 'Andamento da Gennaio Leggeri', 'Andamento da Gennaio Pesanti']
            label: 'Andamento 1'
            size: [110, 90]
            y_label: '%'
            x_label: ''
            save_img: $__radar_andamenti_leggeri-pesanti.png
        image_2:
            filename: TGM.csv
            set_index: Date
            columns_to_filter: ['Andamento da Gennaio(%)']
            label: 'Andamento 2'
            size: [110, 90]
            y_label: '%'
            x_label: ''
            save_img: $__radar_andamenti.png


